# Generated by Django 2.2.4 on 2020-06-24 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_initial', models.CharField(max_length=1)),
                ('rank', models.CharField(max_length=255)),
                ('military_email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('leadership_type', models.CharField(max_length=255)),
                ('hq', models.IntegerField(default=1)),
                ('platoon', models.CharField(blank=True, max_length=255, null=True)),
                ('squad', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('civilian_email', models.CharField(max_length=255)),
                ('unit_origin', models.CharField(max_length=255)),
                ('unit_destination', models.CharField(max_length=255)),
                ('plans_after', models.TextField()),
                ('military_schools', models.TextField()),
                ('civilian_school', models.CharField(max_length=255)),
                ('num_credits', models.IntegerField()),
                ('major', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('attribute_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main.User')),
            ],
        ),
    ]
